version: '3'

services:
  mongodb:
    image: mongo:latest  # Utilize a versão desejada
    container_name: my-mongodb-container
    ports:
      - "27017:27017"  # Conectar na porta padrão do MongoDB
    volumes:
      - mongodb-data:/data/db  # Mapeamento de volume para persistir os dados

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "8002:8081"  # Conectar na porta 8001

volumes:
  mongodb-data:  # Definição do volume
